### ISSUE TITLE
Csv data not populating

### ISSUE THREAD

**Issue by miguelcarvajal** [everypolitician/jekyll-remote_csv#8]
Hi, again, @chrismytton 

Thank you for your help. I have installed the Gem properly and I wrote the template to gather the csv data from a Google Spreadsheet csv file but it doesn't render any data. I've tried also with your csv file in the example. My process was as follow:
- Installed the gem
- `Bundle`
- added `remote_csv` to `config.yml`
- Liquid template
- `bundle exec jekyll serve`

But nothing happens and the data is not populated.

If you have any tip to fix this, I would appreciate it. This is not urgent for me, so please take your time.

Thank you very much!

**Comment by chrismytton** [comment]
@miguelcarvajal Sorry for taking so long to get back to you!

Do you have a minimal example of what you've done that I could take a look at? Perhaps in a GitHub repository or similar?

For starters here's what each bit should look like:

#### Gemfile

``` ruby
group :jekyll_plugins do
  gem 'jekyll-remote_csv'
end
```

#### _config.yml

``` yaml
remote_csv:
  education:
    source: https://docs.google.com/spreadsheets/u/1/d/1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM/export?format=csv
```

#### education.html

``` liquid
{% for item in site.education %}
  <p>{{ item.role }}</p>
{% endfor %}
```
